import { describe, expect, it } from 'vitest';
import { applySourceFixes, normaliseSource } from '../../../scripts/content/discover';
import { IssueCollector, formatIssue } from '../../../scripts/content/errors';
import { buildDoc } from '../../../scripts/content/meta';
import type { Block } from '../../../src/lib/content/schema';
import { afMarkers, codes, enMarkers, parseMd, readCorpus, realEntry } from './helpers';

const kinds = (blocks: readonly Block[]): string[] =>
  blocks.map((block) => `${block.id}:${block.kind}`);

function footerOf(id: string): string {
  const source = readCorpus(realEntry(id));
  const start = source.lastIndexOf('\n---\n');
  return source.slice(start);
}

describe('footer', () => {
  it.each([
    ['core/register', '2026-09-13', 'links to ../05 and ../00'],
    ['lookup/glossary', '2026-09-13', 'links inside the Look it up folder'],
    ['start/how-to-use', '2026-09-13', 'links inside the Start here folder'],
    ['core/you-are-the-business', '2026-09-14', 'dated 14 September'],
  ])('strips the %s footer (%s, %s) into doc.generated', (id, date) => {
    const entry = realEntry(id, {
      kind: 'guide',
      hideSections: undefined,
      blockOverrides: undefined,
      fenceOverrides: undefined,
    });
    const { parsed, issues } = parseMd(`# Title\n\nBody text.\n\n${footerOf(id)}`, entry);
    expect(codes(issues)).toEqual([]);
    expect(parsed.generated).toEqual({ date, tool: 'Claude, Anthropic' });
    expect(kinds(parsed.blocks)).toEqual(['intro.1:paragraph']);
  });

  it('keeps documents without a footer intact', () => {
    const { parsed, issues } = parseMd(
      '# QUOTATION\n\nBody.\n\n---\n\n*Fill this in.*\n',
      realEntry('paperwork/templates/quotation'),
    );
    expect(codes(issues)).toEqual([]);
    expect(parsed.generated).toBeUndefined();
    expect(kinds(parsed.blocks)).toEqual(['intro.1:paragraph', 'intro.2:hr', 'intro.3:note']);
  });

  it.each([
    [
      '# T\n\nBody.\n\n*Generated by AI (Claude, Anthropic) on 13 September 2026.*\n',
      'footer-without-rule',
    ],
    [
      '# T\n\n*Generated by AI (Claude, Anthropic) on 13 September 2026.*\n\nMore.\n',
      'footer-misplaced',
    ],
    ['# T\n\nBody.\n\n---\n\n*Generated by AI at some point.*\n', 'footer-unparsed'],
  ])('reports a malformed footer: %j', (markdown, code) => {
    expect(codes(parseMd(markdown, realEntry('core/register')).issues)).toContain(code);
  });
});

describe('words used in this file', () => {
  const markdown = [
    '# Tax',
    '',
    'Intro.',
    '',
    '## Words used in this file',
    '',
    'Plain meanings. The full list is in [Glossary](../05%20Look%20it%20up/01-glossary.md).',
    '',
    '| Word | Meaning |',
    '|---|---|',
    '| IRP6 | The **short** form. |',
    '| VAT | 15% tax. |',
    '',
    '## Next',
    '',
    'Text.',
  ].join('\n');

  it('becomes a terms block and doc.terms', () => {
    const { parsed, issues } = parseMd(markdown, realEntry('core/tax-and-sars'));
    expect(codes(issues)).toEqual([]);
    expect(kinds(parsed.blocks)).toEqual([
      'intro.1:paragraph',
      'words-used-in-this-file:heading',
      'words-used-in-this-file.1:terms',
      'next:heading',
      'next.1:paragraph',
    ]);
    const doc = buildDoc(
      parsed,
      { status: 'source', sourceLang: 'en' },
      {
        sources: { entries: [], acts: [] },
        generated: { date: '2026-09-13', tool: 'Claude (Anthropic)' },
        verification: { status: 'ai-checked', checkedOn: '2026-09-13' },
      },
    );
    expect(doc.generated).toEqual({ date: '2026-09-13', tool: 'Claude (Anthropic)' });
    expect(doc.terms).toEqual([
      { term: 'IRP6', meaning: 'The short form.' },
      { term: 'VAT', meaning: '15% tax.' },
    ]);
    expect(parsed.links).toEqual([
      {
        from: 'core/tax-and-sars',
        block: 'words-used-in-this-file.1',
        doc: 'lookup/glossary',
        anchor: undefined,
      },
    ]);
  });

  it('reports a heading that is not followed by an intro and a two-column table', () => {
    expect(
      codes(
        parseMd('# T\n\n## Words used in this file\n\n- a list\n', realEntry('core/tax-and-sars'))
          .issues,
      ),
    ).toEqual(['terms-structure']);
    expect(
      codes(
        parseMd(
          '# T\n\n## Words used in this file\n\nIntro.\n\n| A | B | C |\n|---|---|---|\n| 1 | 2 | 3 |\n',
          realEntry('core/tax-and-sars'),
        ).issues,
      ),
    ).toEqual(['terms-structure']);
  });
});

describe('pseudo headings', () => {
  const checklist =
    '# Master checklist\n\n## Part B\n\n**Before you trade**\n- [ ] One\n\n**Vehicle dealer** (`04-business-types/01`)\n- [ ] BRNC\n';

  it('promotes bold-only lines to depth-4 headings and captures the ref', () => {
    const { parsed, issues } = parseMd(checklist, realEntry('lookup/checklist'));
    expect(codes(issues)).toEqual([]);
    expect(kinds(parsed.blocks)).toEqual([
      'part-b:heading',
      'before-you-trade:heading',
      'before-you-trade.1:tasklist',
      'vehicle-dealer:heading',
      'vehicle-dealer.1:tasklist',
    ]);
    const dealer = parsed.blocks[3];
    expect(
      dealer?.kind === 'heading' && {
        depth: dealer.depth,
        pseudo: dealer.pseudo,
        ref: dealer.ref,
        text: dealer.text,
      },
    ).toEqual({
      depth: 4,
      pseudo: true,
      ref: 'business-types/vehicle-dealer',
      text: 'Vehicle dealer',
    });
    expect(parsed.legacy).toEqual([
      {
        doc: 'lookup/checklist',
        block: 'vehicle-dealer',
        code: '04-business-types/01',
        target: 'business-types/vehicle-dealer',
      },
    ]);
  });

  it('reports a ref that does not resolve to a document', () => {
    expect(
      codes(
        parseMd('# T\n\n**Folder** (`04-business-types/`)\n', realEntry('lookup/checklist')).issues,
      ),
    ).toEqual(['pseudo-heading-ref']);
  });

  it.each([
    ['paperwork/templates/quotation', 'a template'],
    ['lookup/sources', 'the sources register'],
  ])('does not promote bold-only lines in %s (%s)', (id) => {
    const { parsed } = parseMd('# T\n\n**[YOUR BUSINESS NAME]**\n', realEntry(id));
    expect(parsed.blocks.map((block) => block.kind)).toEqual(['paragraph']);
  });
});

describe('callouts', () => {
  it('pairs "In plain words" with the previous block and strips the label', () => {
    const { parsed } = parseMd(
      '# T\n\nLegal text.\n\n> **In plain words:** Simple text.\n\n> A note.\n',
      realEntry('core/register'),
    );
    expect(parsed.blocks.slice(1)).toEqual([
      {
        id: 'intro.2',
        hash: expect.any(String) as string,
        kind: 'callout',
        style: 'plain',
        pairsWith: 'intro.1',
        c: [{ t: 'text', v: 'Simple text.' }],
      },
      {
        id: 'intro.3',
        hash: expect.any(String) as string,
        kind: 'callout',
        style: 'note',
        c: [{ t: 'text', v: 'A note.' }],
      },
    ]);
  });

  it('reports a multi-paragraph blockquote', () => {
    expect(codes(parseMd('# T\n\n> One.\n>\n> Two.\n', realEntry('core/register')).issues)).toEqual(
      ['unsupported-blockquote'],
    );
  });
});

describe('templates', () => {
  it('keeps line breaks, signature lines, italic notes, placeholders and unlabeled blockquotes', () => {
    const markdown =
      '# RECEIPT\n\n*Send this when money arrives.*\n\n**[YOUR BUSINESS NAME]**\n[Phone] | [Email]\n\nSigned: ______________________________\n\n> Only send a receipt once the money is in your balance.\n';
    const { parsed, issues } = parseMd(markdown, realEntry('paperwork/templates/receipt'));
    expect(codes(issues)).toEqual([]);
    expect(parsed.blocks.map(({ hash: _hash, ...block }) => block)).toEqual([
      { id: 'intro.1', kind: 'note', c: [{ t: 'text', v: 'Send this when money arrives.' }] },
      {
        id: 'intro.2',
        kind: 'paragraph',
        c: [
          {
            t: 'strong',
            c: [
              { t: 'placeholder', v: 'YOUR BUSINESS NAME', style: 'identity', key: 'businessName' },
            ],
          },
          { t: 'br' },
          { t: 'placeholder', v: 'Phone', style: 'identity', key: 'phone' },
          { t: 'text', v: ' | ' },
          { t: 'placeholder', v: 'Email', style: 'identity', key: 'email' },
        ],
      },
      { id: 'intro.3', kind: 'paragraph', c: [{ t: 'text', v: 'Signed: ' }, { t: 'sigline' }] },
      {
        id: 'intro.4',
        kind: 'callout',
        style: 'note',
        c: [{ t: 'text', v: 'Only send a receipt once the money is in your balance.' }],
      },
    ]);
  });

  it('does not create placeholders in guides', () => {
    const { parsed } = parseMd(
      '# T\n\nFill in every [SQUARE BRACKET] and [Company Name] (Pty) Ltd.\n',
      realEntry('start/how-to-use'),
    );
    expect(parsed.blocks[0]?.kind === 'paragraph' && parsed.blocks[0].c).toEqual([
      { t: 'text', v: 'Fill in every [SQUARE BRACKET] and [Company Name] (Pty) Ltd.' },
    ]);
  });
});

describe('lists and task lists', () => {
  it('normalises an ordered list under a checklist heading and uses the "…:" paragraph as its group', () => {
    const markdown =
      '# T\n\n## Quick answer\n\nRequired, in this order:\n\n1. A\n2. B\n\nOptional but often needed:\n\n8. C\n\n## Your startup checklist\n\nBefore your first purchase:\n\n1. Decide (`01-core/02`)\n2. If working from home: check zoning\n\nBefore your first sale:\n\n11. Roadworthy\n';
    const { parsed, issues } = parseMd(markdown, realEntry('business-types/vehicle-dealer'));
    expect(codes(issues)).toEqual([]);
    expect(kinds(parsed.blocks)).toEqual([
      'quick-answer:heading',
      'quick-answer.1:paragraph',
      'quick-answer.2:list',
      'quick-answer.3:paragraph',
      'quick-answer.4:list',
      'your-startup-checklist:heading',
      'your-startup-checklist.1:tasklist',
      'your-startup-checklist.2:tasklist',
    ]);
    const [, , first, , second, , tasks, later] = parsed.blocks;
    expect(first?.kind === 'list' && first.start).toBe(1);
    expect(second?.kind === 'list' && second.start).toBe(8);
    expect(tasks?.kind === 'tasklist' && tasks.group).toEqual([
      { t: 'text', v: 'Before your first purchase' },
    ]);
    expect(later?.kind === 'tasklist' && later.group).toEqual([
      { t: 'text', v: 'Before your first sale' },
    ]);
    expect(tasks?.kind === 'tasklist' && tasks.items.map((item) => item.c)).toEqual([
      [
        { t: 'text', v: 'Decide (' },
        { t: 'docref', doc: 'core/register', label: '01-core/02' },
        { t: 'text', v: ')' },
      ],
      [{ t: 'text', v: 'If working from home: check zoning' }],
    ]);
  });

  it('turns - [ ] lists into task lists anywhere', () => {
    const { parsed } = parseMd(
      '# T\n\n## Anything\n\n- [ ] One\n- [x] Two\n',
      realEntry('core/register'),
    );
    expect(parsed.blocks.map((block) => block.kind)).toEqual(['heading', 'tasklist']);
  });

  it.each([
    ['# T\n\n- [ ] One\n- Two\n', 'mixed-tasklist'],
    ['# T\n\n- One\n\n  Second paragraph\n- Two\n', 'unsupported-list-item'],
  ])('reports %j', (markdown, code) => {
    expect(codes(parseMd(markdown, realEntry('core/register')).issues)).toContain(code);
  });
});

describe('fences', () => {
  const fence = (text: string): string => `\`\`\`\n${text}\n\`\`\``;

  it('classifies the five variants', () => {
    const markdown = [
      '# T',
      fence(
        '[YOUR BUSINESS NAME]\n-------------------------------------------------------------\nTotal R 0.00',
      ),
      fence('07 Brand/\n├── logo/\n└── fonts/'),
      fence('I like option [NUMBER] best.'),
      fence('MOKOENA MOTORS\nA trading name of Mokoena Holdings (Pty) Ltd'),
      fence('One\nTwo\nThree\nFour'),
    ].join('\n\n');
    const { parsed, issues } = parseMd(
      markdown,
      realEntry('paperwork/free-tools', { fenceOverrides: { 'intro.5': 'snippet' } }),
    );
    expect(codes(issues)).toEqual([]);
    expect(
      parsed.fences.map((record) => `${record.block}:${record.variant}:${record.rule}`),
    ).toEqual([
      'intro.1:template-preview:hyphen-rule',
      'intro.2:listing:box-drawing',
      'intro.3:prompt:prompt-heuristic',
      'intro.4:example:short',
      'intro.5:snippet:override',
    ]);
    const preview = parsed.blocks[0];
    expect(preview?.kind === 'code' && preview.placeholders).toEqual([
      { t: 'placeholder', v: 'YOUR BUSINESS NAME', style: 'identity', key: 'businessName' },
    ]);
    const example = parsed.blocks[3];
    expect(example?.kind === 'code' && example.placeholders).toBeUndefined();
  });

  it('uses the doc default before the prompt heuristic', () => {
    const { parsed } = parseMd(
      `# T\n\n${fence('Line one\nLine two\nLine three\nLine four')}`,
      realEntry('start/what-has-changed'),
    );
    expect(parsed.fences[0]?.rule).toBe('doc-default');
    expect(parsed.fences[0]?.variant).toBe('snippet');
  });

  it('fails on an unclassified fence and on an override for a fence that does not exist', () => {
    expect(
      codes(
        parseMd(
          `# T\n\n${fence('One\nTwo\nThree\nFour')}`,
          realEntry('paperwork/free-tools', { fenceOverrides: {} }),
        ).issues,
      ),
    ).toEqual(['unclassified-fence']);
    expect(codes(parseMd('# T\n\nText.\n', realEntry('paperwork/free-tools')).issues)).toEqual([
      'unknown-override',
    ]);
  });
});

describe('structural overrides', () => {
  it('replaces the stale folder tree with a toc block and hides sections', () => {
    const { parsed, issues } = parseMd(
      readCorpus(realEntry('start/start-here')),
      realEntry('start/start-here'),
    );
    expect(codes(issues)).toEqual([]);
    const tree = parsed.blocks.find((block) => block.id === 'what-is-in-here.1');
    expect(tree?.kind).toBe('toc');
    expect(parsed.rawKinds[parsed.blocks.indexOf(tree as Block)]).toBe('code');

    const hidden = parseMd(
      '# T\n\n## Keep\n\nA.\n\n## Hide me\n\nB.\n\n### Inside\n\nC.\n\n## After\n\nD.\n',
      realEntry('start/how-to-use', { hideSections: ['hide-me'], special: {} }),
    );
    expect(hidden.parsed.blocks.filter((block) => block.hidden).map((block) => block.id)).toEqual([
      'hide-me',
      'hide-me.1',
      'inside',
      'inside.1',
    ]);
  });

  it('reports overrides for missing blocks and headings', () => {
    const { issues } = parseMd(
      '# T\n\nText.\n',
      realEntry('start/start-here', { hideSections: ['nope'] }),
    );
    expect(codes(issues)).toEqual(['unknown-override', 'unknown-override']);
  });
});

describe('unsupported markdown', () => {
  it.each([
    ['# T\n\n<div>html</div>\n', 'unsupported-block'],
    ['# T\n\n# Second title\n', 'extra-h1'],
    ['Text before the title.\n', 'missing-h1'],
    ['# T\n\n#### Too deep\n', 'unsupported-heading-depth'],
    ['# T\n\nAn ![image](x.png) here.\n', 'unsupported-inline'],
    ['# T\n\nSee [missing](99-nope.md).\n', 'unresolved-link'],
    ['# T\n\nSee `01-core/99`.\n', 'unresolved-legacy-ref'],
  ])('%j → %s', (markdown, code) => {
    expect(codes(parseMd(markdown, realEntry('core/register')).issues)).toContain(code);
  });
});

describe('source normalisation', () => {
  it('parses CRLF exactly like LF', () => {
    const source = readCorpus(realEntry('business-types/food'));
    const lf = parseMd(source, realEntry('business-types/food')).parsed;
    const crlf = parseMd(source.replace(/\n/g, '\r\n'), realEntry('business-types/food')).parsed;
    expect(crlf.blocks).toEqual(lf.blocks);
    expect(crlf.contentHash).toBe(lf.contentHash);
  });

  it('strips a leading byte-order mark and nothing else', () => {
    expect(normaliseSource(`${String.fromCharCode(0xfeff)}# T\r\nFEFF stays\r`)).toBe(
      '# T\nFEFF stays\n',
    );
  });

  it('applies a source fix only when it matches exactly once', () => {
    const issues = new IssueCollector();
    const entry = realEntry('core/start-here');
    const fixed = applySourceFixes(
      'x\nthe habits that stop you being scammed.\n3. Pick a name',
      entry,
      'en',
      enMarkers(),
      issues,
    );
    expect(fixed).toContain('scammed.\n\n3. Pick');
    expect(applySourceFixes('no match here', entry, 'en', enMarkers(), issues)).toBe(
      'no match here',
    );
    expect(applySourceFixes('no match here', entry, 'af', afMarkers(), issues)).toBe(
      'no match here',
    );
    expect(codes(issues)).toEqual(['source-fix']);
  });

  it('fixes the start-here list quirk in a translation, with or without the blank line already there', () => {
    const entry = realEntry('core/start-here');
    const issues = new IssueCollector();
    const copied =
      '# Begin\n\n## Volgorde\n\n1. Verkoop iets.\n2. Maak ’n bankrekening oop.\n\n As jy van die huis af werk, lees eers dit.\n3. Kies ’n naam.\n4. Maak sjablone.\n';
    const fixed = applySourceFixes(copied, entry, 'af', afMarkers(), issues);
    expect(fixed).toContain('lees eers dit.\n\n3. Kies');
    expect(applySourceFixes(fixed, entry, 'af', afMarkers(), issues)).toBe(fixed);
    const unindented = copied.replace('\n As jy', '\nAs jy');
    expect(applySourceFixes(unindented, entry, 'af', afMarkers(), issues)).toContain(
      'dit.\n\n3. Kies',
    );
    // Anchored to the "2. " line: another note directly above a "3. " elsewhere is left alone.
    const elsewhere = `${fixed}\n## Nog iets\n\n Die drie dinge:\n3. Derde ding.\n`;
    expect(applySourceFixes(elsewhere, entry, 'af', afMarkers(), issues)).toBe(elsewhere);
    expect(codes(issues)).toEqual([]);
    expect(kinds(parseMd(fixed, entry, 'af').parsed.blocks)).toEqual([
      'volgorde:heading',
      'volgorde.1:list',
      'volgorde.2:paragraph',
      'volgorde.3:list',
    ]);
    const twice = `${copied}\n2. Weer ’n stap.\n\n Nog ’n nota.\n3. Weer.\n`;
    applySourceFixes(twice, entry, 'af', afMarkers(), issues);
    applySourceFixes(fixed, entry, 'en', enMarkers(), issues);
    expect(issues.issues.map((issue) => issue.message)).toEqual([
      'expected at most one match for the sourceFixes pattern "^(2\\\\. [^\\\\n]*\\\\n\\\\n?)( ?[^\\\\s\\\\d-][^\\\\n]*)\\\\n(3\\\\. )", found 2',
      'expected exactly one match for a sourceFixes "find", found 0',
    ]);
  });

  it('refuses a source fix that would change a fact', () => {
    const issues = new IssueCollector();
    const entry = {
      ...realEntry('core/start-here'),
      sourceFixes: [
        {
          lang: 'en' as const,
          find: 'pay R100',
          replace: 'pay R200',
          reason: 'A fix that changes an amount, which the guard must refuse.',
        },
      ],
    };
    expect(applySourceFixes('You pay R100 once.', entry, 'en', enMarkers(), issues)).toBe(
      'You pay R100 once.',
    );
    expect(issues.issues.map((issue) => issue.message)).toEqual([
      'a sourceFix changed a fact, which a fix may never do (it repairs markdown structure only). Correct the fact in the English source instead',
    ]);
  });

  it('reads an Afrikaans source fix with Afrikaans markers, so an ordinal or a month change is refused', () => {
    const fix = (find: string, replace: string) => ({
      ...realEntry('core/start-here'),
      sourceFixes: [
        {
          lang: 'af' as const,
          find,
          replace,
          reason: 'A translation fix that changes a fact, which the guard must refuse.',
        },
      ],
    });
    const cases: [string, string, string][] = [
      ['Betaal teen die 7de van die maand.', 'die 7de', 'die 8ste'],
      ['Dien in teen 31 Augustus.', '31 Augustus', '31 September'],
      ['Dien in teen einde Augustus.', 'einde Augustus', 'einde September'],
    ];
    for (const [text, find, replace] of cases) {
      const issues = new IssueCollector();
      expect(applySourceFixes(text, fix(find, replace), 'af', afMarkers(), issues), text).toBe(
        text,
      );
      expect(codes(issues), text).toEqual(['source-fix-facts']);
    }
    // The English markers do not read `7de` or `Augustus`, which is why the language's own are passed.
    const english = new IssueCollector();
    applySourceFixes(cases[0]![0], fix('die 7de', 'die 8ste'), 'af', enMarkers(), english);
    expect(codes(english)).toEqual([]);
    // A structural fix in Afrikaans still applies.
    const structural = new IssueCollector();
    expect(
      applySourceFixes('Die 7de.\n3. Kies', fix('.\n3.', '.\n\n3.'), 'af', afMarkers(), structural),
    ).toBe('Die 7de.\n\n3. Kies');
    expect(codes(structural)).toEqual([]);
  });
});

describe('email addresses, bare domains and error locations', () => {
  it('keeps a bare email address as text and rejects an explicit mailto link', () => {
    const { parsed, issues } = parseMd(
      '# T\n\nEmail info@yourbusiness.co.za today.\n',
      realEntry('core/register'),
    );
    expect(codes(issues)).toEqual([]);
    expect(parsed.blocks[0]).toEqual(
      expect.objectContaining({
        kind: 'paragraph',
        c: [{ t: 'text', v: 'Email info@yourbusiness.co.za today.' }],
      }),
    );
    const explicit = parseMd(
      '# T\n\nWrite to [us](mailto:a@b.co.za).\n',
      realEntry('core/register'),
    );
    expect(explicit.issues.issues.map(formatIssue)).toEqual([
      '01 Core - applies to everyone/02-register.md:3: core/register:intro.1: unsupported-link: email links are not supported ("mailto:a@b.co.za"); write the address as plain text',
    ]);
  });

  it('fails on a bare domain that is not on the allow list, naming file and line', () => {
    const { parsed, issues } = parseMd(
      '# T\n\nBody.\n\nUse yourshop.co.za or cars.co.za as an example.\n',
      realEntry('core/register'),
    );
    expect(issues.issues.map(formatIssue)).toEqual([
      '01 Core - applies to everyone/02-register.md:5: core/register:intro.2: unknown-bare-domain: "yourshop.co.za" would become a link to yourshop.co.za. Add a real host to linkify.allowDomains, or an example name to linkify.ignoreDomains, in docs.meta.json',
    ]);
    expect(parsed.bareDomains).toEqual(['yourshop.co.za', 'cars.co.za']);
  });

  it('names the file and line for structural errors', () => {
    const { issues } = parseMd(
      '# T\n\nText.\n\n<div>html</div>\n',
      realEntry('core/register'),
      'en',
    );
    expect(issues.issues.map(formatIssue)).toEqual([
      '01 Core - applies to everyone/02-register.md:5: core/register:intro: unsupported-block: unsupported markdown node "html"',
    ]);
  });
});
