import type {
  Doc,
  DocKind,
  DocSources,
  SectionId,
  SourceNote,
  SourcesFile,
  Verification,
} from '../../src/lib/content/schema';
import type { ContentConfig, DocMetaEntry, SourceMap } from './config';
import type { IssueCollector } from './errors';
import type { ParsedDoc } from './parse';
import type { Generated } from './special/footer';

/** Everything a page needs to say it was generated by AI, how it was checked and what it is based on. */
export interface DocProvenance {
  sources: DocSources;
  sourceNote?: SourceNote | undefined;
  /** Used only when the markdown has no generated-by-AI footer. */
  generated: Generated;
  verification: Verification;
}

/** Kinds and sections whose documents must list at least one source, or carry a source note. */
export const SOURCES_REQUIRED: { kinds: readonly DocKind[]; sections: readonly SectionId[] } = {
  kinds: ['guide', 'template', 'checklist'],
  sections: ['core', 'branding', 'paperwork', 'business-types', 'lookup'],
};

export function requiresSources(entry: Pick<DocMetaEntry, 'kind' | 'section'>): boolean {
  return (
    SOURCES_REQUIRED.kinds.includes(entry.kind) && SOURCES_REQUIRED.sections.includes(entry.section)
  );
}

/**
 * `https://www.SARS.gov.za/a/b/?x=1#top` → `sars.gov.za/a/b?x=1`: lower-case host without `www.`, no
 * trailing slash, query kept, fragment dropped. `undefined` for a value that is not a URL.
 */
export function normaliseSourceUrl(href: string): string | undefined {
  try {
    const url = new URL(href);
    const host = url.hostname.toLowerCase().replace(/^www\./, '');
    return `${host}${url.pathname.replace(/\/+$/, '')}${url.search}`;
  } catch {
    return undefined;
  }
}

/** A link to a site's front page names the site, not the page that supports a claim. */
function isFrontPage(key: string): boolean {
  return !key.includes('/') && !key.includes('?');
}

export interface MapSourcesInput {
  parsed: readonly ParsedDoc[];
  sources: SourcesFile | undefined;
  sourceMap: SourceMap;
  issues: IssueCollector;
  /** `provenance.json` sourceNoteExemptions: documents allowed a note although they must list sources. */
  exemptions?: Readonly<Record<string, string>>;
  /**
   * The sources register, the one document exempt from `source-note-with-evidence`. Identified by id,
   * not by kind: `DocsMetaSchema` already refuses a second `kind: "sources"` entry, and naming the
   * document here means a page cannot claim the exemption by relabelling itself.
   */
  registerDocId?: string | undefined;
}

/**
 * Per-document sources (English; translations copy them). Evidence, in order:
 * 1. an external link or bare URL in the document whose host, path and query equal a register entry's
 *    link (front-page links do not count);
 * 2. the document is listed under "Where it appears" for an act;
 * 3. `content-meta/source-map.json`: register groups or entries mapped to documents, each with a reason.
 *
 * Documents listed under `notes.docs` get a `sourceNote` (pointing at `notes.see`) and no source list.
 * A guide, template or checklist in core, branding, paperwork, business-types or lookup without any source
 * or note is a build error. So is a note on any document for which evidence 1 or 2 exists: that evidence
 * must be mapped, and no exemption can excuse it.
 *
 * That last check is a backstop over links and "Where it appears" rows, not a proof that a noted page
 * makes no claim. It cannot see a claim resting on a register entry the page does not link, a link that
 * differs from the entry's by its query string, or a link to an entry whose URL is a site front page.
 * Judging whether a noted page states a fact it should source is the accuracy review's job (ADR-0006
 * decision 4), not this function's.
 */
export function mapDocSources(
  input: MapSourcesInput,
): Map<string, { sources: DocSources; sourceNote?: SourceNote }> {
  const { parsed, sources, sourceMap, issues } = input;
  const entries = sources?.entries ?? [];
  const acts = sources?.acts ?? [];
  const docIds = new Set(parsed.map((doc) => doc.entry.id));
  const entryOrder = new Map(entries.map((entry, index) => [entry.id, index]));
  const actOrder = new Map(acts.map((act, index) => [act.id, index]));
  const notes = sourceMap.notes.docs;
  const where = 'content-meta/source-map.json';

  const byUrl = new Map<string, string[]>();
  for (const entry of entries) {
    for (const url of new Set([...(entry.url ? [entry.url] : []), ...entry.urls])) {
      const key = normaliseSourceUrl(url);
      if (key === undefined || isFrontPage(key)) continue;
      const ids = byUrl.get(key) ?? [];
      if (!ids.includes(entry.id)) ids.push(entry.id);
      byUrl.set(key, ids);
    }
  }

  const found = new Map<string, Set<string>>();
  for (const doc of parsed) {
    const ids = new Set<string>();
    for (const href of doc.externalLinks) {
      const key = normaliseSourceUrl(href);
      for (const id of key === undefined ? [] : (byUrl.get(key) ?? [])) ids.add(id);
    }
    found.set(doc.entry.id, ids);
  }

  const mappedActs = new Map<string, Set<string>>(
    parsed.map((doc) => [doc.entry.id, new Set<string>()]),
  );
  const mapTo = (
    docs: readonly string[],
    ids: readonly string[],
    label: string,
    into: Map<string, Set<string>> = found,
  ): void => {
    for (const doc of docs) {
      if (!docIds.has(doc)) {
        issues.add(
          'source-map',
          `${label} maps to "${doc}", which is not a document`,
          undefined,
          undefined,
          { file: where },
        );
      } else if (notes[doc] !== undefined) {
        issues.add(
          'source-map',
          `${label} maps to "${doc}", which has a source note instead of sources`,
          doc,
          undefined,
          { file: where },
        );
      } else {
        for (const id of ids) into.get(doc)?.add(id);
      }
    }
  };
  const byGroup = new Map<string, string[]>();
  for (const entry of entries)
    byGroup.set(entry.groupId, [...(byGroup.get(entry.groupId) ?? []), entry.id]);
  for (const rule of sourceMap.groups) {
    const ids = byGroup.get(rule.group);
    if (ids === undefined) {
      issues.add(
        'source-map',
        `group "${rule.group}" is not a group of the sources register`,
        undefined,
        undefined,
        { file: where },
      );
      continue;
    }
    mapTo(rule.docs, ids, `group "${rule.group}"`);
  }
  const pairs = new Set<string>();
  for (const rule of sourceMap.entries) {
    if (!entryOrder.has(rule.entry)) {
      issues.add(
        'source-map',
        `entry "${rule.entry}" is not in the sources register`,
        undefined,
        undefined,
        { file: where },
      );
      continue;
    }
    for (const doc of rule.docs) {
      const pair = `${rule.entry} → ${doc}`;
      if (pairs.has(pair))
        issues.add('source-map', `${pair} is listed twice`, doc, undefined, { file: where });
      pairs.add(pair);
    }
    mapTo(rule.docs, [rule.entry], `entry "${rule.entry}"`);
  }
  for (const rule of sourceMap.acts) {
    if (!actOrder.has(rule.act)) {
      issues.add(
        'source-map',
        `act "${rule.act}" is not in the legislation table`,
        undefined,
        undefined,
        { file: where },
      );
      continue;
    }
    mapTo(rule.docs, [rule.act], `act "${rule.act}"`, mappedActs);
  }
  for (const doc of [...Object.keys(notes), ...sourceMap.notes.see]) {
    if (!docIds.has(doc))
      issues.add(
        'source-map',
        `note refers to "${doc}", which is not a document`,
        undefined,
        undefined,
        { file: where },
      );
  }

  const result = new Map<string, { sources: DocSources; sourceNote?: SourceNote }>();
  for (const doc of parsed) {
    const id = doc.entry.id;
    const reason = notes[id];
    /*
     * A note says a page makes no claim the register supports. When the register itself links a page to
     * a source (an act's "Where it appears" row lists it, or the page links to a register entry), that is
     * untrue, and no note or exemption may hide it. There is no override: map the evidence instead. The
     * register document is the one exception, because every link on it is a register entry by definition,
     * and it is excepted by id so that no other page can claim the exception by declaring the kind.
     */
    const evidence =
      reason === undefined || id === input.registerDocId
        ? []
        : [
            ...acts.filter((act) => act.appearsIn.includes(id)).map((act) => `act "${act.id}"`),
            ...[...(found.get(id) ?? [])].map((entry) => `register entry "${entry}"`),
          ];
    if (evidence.length > 0) {
      issues.add(
        'source-note-with-evidence',
        `has a source note, but the sources register has evidence for it: ${evidence.join(', ')}. A page with source evidence must list its sources: remove its note from ${where} (and any sourceNoteExemptions entry in content-meta/provenance.json) and map that evidence in ${where} with a reason`,
        id,
      );
    }
    if (reason !== undefined && requiresSources(doc.entry) && !input.exemptions?.[id]) {
      issues.add(
        'source-note-not-allowed',
        `a ${doc.entry.kind} in ${doc.entry.section} must list sources; a note needs a decision recorded in content-meta/provenance.json sourceNoteExemptions`,
        id,
      );
    }
    if (reason !== undefined) {
      result.set(id, {
        sources: { entries: [], acts: [] },
        sourceNote: { reason, see: sourceMap.notes.see.filter((see) => see !== id) },
      });
      continue;
    }
    const entryIds = [...(found.get(id) ?? [])].sort(
      (a, b) => (entryOrder.get(a) ?? 0) - (entryOrder.get(b) ?? 0),
    );
    const mapped = mappedActs.get(id);
    const actIds = acts
      .filter((act) => act.appearsIn.includes(id) || mapped?.has(act.id))
      .map((act) => act.id);
    result.set(id, { sources: { entries: entryIds, acts: actIds } });
    /*
     * An act row that merely lists a document under "Where it appears" is not evidence for that
     * document's claims; the register entries behind the claims are. So a document that must list
     * sources needs a register entry, or an act deliberately mapped to it in source-map.json.
     */
    if (entryIds.length === 0 && (mapped?.size ?? 0) === 0 && requiresSources(doc.entry)) {
      issues.add(
        'doc-without-sources',
        `no sources: no link to a register entry and no mapping in ${where} (an act's "Where it appears" row is not evidence on its own). Map the register entries that support its claims, or give it a note`,
        id,
      );
    }
  }
  return result;
}

/**
 * `ai-checked` on the register's check date unless `content-meta/provenance.json` records a review.
 *
 * A `human-verified` review carries its own `checkedOn` and `reviewedBy`, both required by the schema.
 * Neither falls back to another date or an empty name, so a page can never say a named person checked
 * it on a day nobody reviewed it.
 */
export function verificationFor(
  docId: string,
  config: ContentConfig,
  registerCheckedOn: string | undefined,
): Verification {
  const override = config.provenance.verification[docId];
  if (override?.status === 'human-verified') {
    return {
      status: 'human-verified',
      checkedOn: override.checkedOn,
      reviewedBy: override.reviewedBy,
    };
  }
  // An `ai-checked` override always states its own `checkedOn` (with the reason for it), so the
  // fallbacks below apply only to a document with no override at all.
  return {
    status: 'ai-checked',
    checkedOn: override?.checkedOn ?? registerCheckedOn ?? config.provenance.generated.date,
  };
}

/** The project's reviewers work in South Africa, so "today" is the calendar date in Johannesburg. */
export const REVIEW_TIME_ZONE = 'Africa/Johannesburg';

/** `YYYY-MM-DD` for `now` in `Africa/Johannesburg` (UTC+2): 23:30 UTC on 16 September is 17 September. */
export function todayInJohannesburg(now: Date = new Date()): string {
  // `en-CA` writes a short date as YYYY-MM-DD.
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: REVIEW_TIME_ZONE,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(now);
}

/**
 * Verification overrides must name built documents and be dated on or before the day of the build.
 * Source-note exemptions must belong to a document that has a note and actually needs the exemption.
 */
export function checkProvenanceConfig(
  config: ContentConfig,
  docIds: ReadonlySet<string>,
  issues: IssueCollector,
  today: string = todayInJohannesburg(),
): void {
  for (const [docId, review] of Object.entries(config.provenance.verification)) {
    if (!docIds.has(docId)) {
      issues.add(
        'unknown-override',
        `provenance.json verification lists "${docId}", which is not a document`,
        undefined,
        undefined,
        { file: 'content-meta/provenance.json' },
      );
    }
    // Both kinds of review require `checkedOn`, so there is no undated review to skip here.
    if (review.checkedOn > today) {
      issues.add(
        'verification-date',
        `provenance.json verification "${docId}": checkedOn ${review.checkedOn} is in the future (today is ${today}); a review cannot be recorded before it happens`,
        docIds.has(docId) ? docId : undefined,
        undefined,
        { file: 'content-meta/provenance.json' },
      );
    }
  }
  for (const docId of Object.keys(config.provenance.sourceNoteExemptions)) {
    if (!docIds.has(docId) || config.sourceMap.notes.docs[docId] === undefined) {
      issues.add(
        'unknown-override',
        `provenance.json sourceNoteExemptions lists "${docId}", which is not a document with a source note`,
        undefined,
        undefined,
        { file: 'content-meta/provenance.json' },
      );
      continue;
    }
    const entry = config.docsMeta.docs.find((doc) => doc.id === docId);
    if (entry !== undefined && !requiresSources(entry)) {
      issues.add(
        'unknown-override',
        `provenance.json sourceNoteExemptions lists "${docId}", which does not need one: a ${entry.kind} in ${entry.section} may carry a source note without an exemption`,
        docId,
        undefined,
        { file: 'content-meta/provenance.json' },
      );
    }
  }
}

/**
 * A page can never say it was checked before it was written. The later date is not used instead, because
 * nobody recorded a check on that day: the author records the real check date, with its evidence, in
 * `content-meta/provenance.json` verification.
 */
export function checkVerificationDates(
  docs: readonly Pick<Doc, 'id' | 'lang' | 'generated' | 'verification'>[],
  issues: IssueCollector,
): void {
  for (const doc of docs) {
    if (doc.verification.checkedOn >= doc.generated.date) continue;
    issues.add(
      'verification-date',
      `${doc.lang}: checked on ${doc.verification.checkedOn}, before it was generated on ${doc.generated.date}. A page cannot be checked before it is written: record the date its facts were really checked, and the evidence for that date, in content-meta/provenance.json verification`,
      doc.id,
    );
  }
}
